#- list of names of dynamically loaded trackers
trackers : [
  "MpcTracker",
  "LandoffTracker",
  "JoyTracker",
  "NullTracker",
]

safety:

  tilt_limit:

    eland:
      enabled: false
      limit: deg(75) # [rad]

    disarm:
      enabled: true
      limit: deg(90) # [rad]

  tilt_error_disarm:
    enabled: true
    timeout: 0.01 # [s] # for how long the error has to be present to disarm
    error_threshold: deg(10) # [rad]

  yaw_error_eland:
    enabled: false
    limit: deg(90) # [rad]

  odometry_max_missing_time: 1.0 # [s]

  odometry_innovation_eland:
    enabled: false

Se3Controller:
  address: "mrs_uav_controllers/Se3Controller"
  namespace: "se3_controller"
  eland_threshold: 3.0 # [m], position error triggering eland
  failsafe_threshold: 3.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 3.0 # [m], position odometry innovation threshold
  human_switchable: true

obstacle_bumper:

  enabled: false
  repulsion:
    enabled: false
