publish_rate:
  main: 40 # [Hz] main and aux odometry

# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "RTK"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "RTK"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["RTK", "GPS"]

heading_estimators:
  active: ["PIXHAWK"]

altitude_estimators: 
  active: ["RTK"] 
