param1: 14.0 #14
param2: 0.88 #0.88
# cohesion
param3: 1.0
# separation
param4: 3.5
param5: 0.8
param6: 0.0
param7: 0.0
param8: 0.0
param9: 0.0


# last successful

# param1: 14.0 #14
# param2: 0.88 #0.88
# # cohesion
# param3: 1.0
# param4: 2.5
# param5: 0.5
# param6: 0.0
# param7: 0.0
# param8: 0.0
# param9: 0.0
