param1: 18.0 #14
param2: 2.0 #0.8
# cohesion
param3: 1.0
param4: 4.5
param5: 0.5
param6: 0.0
param7: 0.0
param8: 0.0
param9: 0.0


# last successful

# param1: 5.0
# # target
# param2: 0.25
# # cohesion
# param3: 0.75
# param4: 1.0
# param5: 0.5
# param6: 0.0
# param7: 0.0
# param8: 0.0
# param9: 0.0