param1: 0.1 #cohesion
param2: 0.6 #separation
param3: 5.0 #avoidance
param4: 1.0 #attraction
param5: 0.5 #theshold angle consensus;
param6: 50 # number of counts after direction selection
param7: 3.0 # distance to gate
param8: 0.8
param9: 0.8 # 0.8 # safety distance
