param1: 0.2 #cohesion
param2: 2.0 #separation
param3: 1.0 #avoidance
param4: 0.2 #attraction
param5: 0.5 #theshold angle consensus;
param6: 50 # number of counts after direction selection
param7: 2.0 #threshold distance
param8: 1.0 # collision avoidance threhold
param9: 0.8 # safety distance
