param1: 0.1 #cohesion
param2: 3.0 #separation
param3: 0.5 #avoidance
param4: 2.0 #attraction
param5: 0.5 #theshold angle consensus;
param6: 20 # number of counts after direction selection
param7: 0.66 # percentage to neighbour
param8: 2.0 # separation drones
param9: 0.5 # separation gates
