param1: 0.2 #cohesion
param2: 0.6 #separation
param3: 1.0 #avoidance
param4: 2.0 #attraction
param5: 1.57 #direction of the target
param6: 0.0
param7: 0.0
param8: 0.0
param9: 0.8 # 0.8 # weighting threshold
