# alignment - velocity
param1: 0.675
# cohesion - hitting each other - bigger -> more closer
param2: 0.750
# separation - wall hitting - bigger -> less hitting
param3: 0.85
# target - beacon - bigger -> closer to beacon
param4: 0.1

# w_beacon
param5: 0.0
# w_neigh
param6: 0.0
# w_own
param7: 0.0
#q - neighbours
param8: 0.0
#r - beacon
param9: 0.0


#last best
# # alignment - velocity
# param1: 0.675
# # cohesion - #hitting each other - bigger -> more closer
# param2: 0.750
# # separation - wall hitting - bigger -> less hitting
# param3: 0.85
# # target - closer to beacon or farther
# param4: 0.125