version: "1.0.0"

classes: 4 # colors

rate: 10000              # (Hz)
stop_after_finish: true  # If to stop the task once it fails

statistical_evaluation:
  repeat: # how many times repeat each variant
    easy:      100
    medium:    50
    difficult: 50
  allowed_failure_rate: 0.10 # (percent)

validation:
  max_dead_ratio: 0.3  # if dead/alive exceeds this threshold, task fails
  max_iterations: 3600 # 2 * 60 * 30 (2 min if run at 30 Hz)

# AGENTS
agents:

  count: 50 # number of agents

  neighborhood:
    radius: 1.5 # visibility radius

  colorblind_ratio: 0.8 # ratio of agents unable to distinguish beacon colors

  # Spawn area
  spawn:
    limits:
      x:
        min: -5.0
        max: 5.0
      y:
        min: -5.0
        max: 5.0

  distribution:
    spawn: [0.25, 0.25, 0.25, 0.25] # chance of choosing one of the four classes at initialization
    prior:
      max_class_prob: 0.5 # probability of the selected class (rest is distributed uniformly)

  # Killing agents
  kill:
    enable: true
    # Agents too close to each other collide
    proximity:
      radius: 0.3
      probability: 0.3
    # Agents outside of safe area are eaten by a predator
    predator:
      distance_from_beacons: 8.0 # distance in each dimension away from the beacons
      probability: 0.01
    # Agents with too few neighbors die of loneliness
    knn:
      radius: 5.0
      min_neighbors: 2
      probability: 0.2

# BEACONS
beacons:
  radius: 1.5         # emission radius
  spawn_distance: 8.0 # length of the square size
  emission_error: 0.5 # probability of incorrect pointer-color sensing by an agent

# AGENT MODEL
constraints:
  velocity:
    min: 0.1
    max: 0.2
  heading:
    max_change: 0.523598776 # (rad) per iteration

# TASKS
tasks:
  easy:
    scoring:
      base: 1
      bonus:
        aliveness: [0.9, 0.8] # has to be given in a descending order
        points:    [2, 1]
    agents:
      count: 50
      kill:
        predator:
          distance_from_beacons: 11.0
    beacons:
      spawn_distance: 8.0

  medium:
    scoring:
      base: 2
      bonus:
        aliveness: [0.95, 0.9, 0.8] # has to be given in a descending order
        points:    [3, 2, 1]
    agents:
      count: 100
      kill:
        predator:
          distance_from_beacons: 13.0
    beacons:
      spawn_distance: 9.0

  difficult:
    scoring:
      base: 3
      bonus:
        aliveness: [0.95, 0.9, 0.85, 0.8, 0.75] # has to be given in a descending order
        points:    [5, 4, 3, 2, 1]
    agents:
      count: 150
      kill:
        predator:
          distance_from_beacons: 17.0
    beacons:
      spawn_distance: 10.0

# VISUALIZATION
visualization:
  frame: "common_origin"
  edges:
    show: True
    lw: 0.05
  agents:
    size:
      pos: 0.12
      vel: 0.1
      dead: 0.3
  environment:
    predator_zone:
      lw: 0.5
    beacons:
      inner:
        size: 0.2
      alpha: 0.2
  arrows:
    shaft_diameter: 0.05
    head_diameter: 0.15
